TP1-Module06/Models/SamouraisViewModel.cs
using BO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TP1_Module06.Models
{
    public class SamouraisViewModel
    {
        public Samourai Samourai { get; set; }

        public int? IdArme { get; set; }

        public List<SelectListItem> Armes { get; set; } = new List<SelectListItem>();

        public List<SelectListItem> ArtMartials { get; set; } = new List<SelectListItem>();

        public List<int> IdArtMartials { get; set; } = new List<int>();
    }
}

TP1-Module06/Controllers/ArtMartialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BO;
using TP1_Module06.Data;

namespace TP1_Module06.Controllers
{
    public class ArtMartialsController : Controller
    {
        private TP1_Module06Context db = new TP1_Module06Context();

        // GET: ArtMartials
        public ActionResult Index()
        {
            return View(db.ArtMartials.ToList());
        }

        // GET: ArtMartials/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArtMartial artMartial = db.ArtMartials.Find(id);
            if (artMartial == null)
            {
                return HttpNotFound();
            }
            return View(artMartial);
        }

        // GET: ArtMartials/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ArtMartials/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom")] ArtMartial artMartial)
        {
            if (ModelState.IsValid)
            {
                db.ArtMartials.Add(artMartial);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(artMartial);
        }

        // GET: ArtMartials/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArtMartial artMartial = db.ArtMartials.Find(id);
            if (artMartial == null)
            {
                return HttpNotFound();
            }
            return View(artMartial);
        }

        // POST: ArtMartials/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom")] ArtMartial artMartial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artMartial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(artMartial);
        }

        // GET: ArtMartials/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArtMartial artMartial = db.ArtMartials.Find(id);
            if (artMartial == null)
            {
                return HttpNotFound();
            }
            return View(artMartial);
        }

        // POST: ArtMartials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ArtMartial artMartial = db.ArtMartials.Find(id);
            db.ArtMartials.Remove(artMartial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TP1-Module06/Controllers/SamouraisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BO;
using TP1_Module06.Data;
using TP1_Module06.Models;

namespace TP1_Module06.Controllers
{
    public class SamouraisController : Controller
    {
        private TP1_Module06Context db = new TP1_Module06Context();

        // GET: Samourais
        public ActionResult Index()
        {
            return View(db.Samourais.Include(a => a.Arme).Include(a => a.ArtMartials).ToList());
        }

        // GET: Samourais/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Samourai samourai = db.Samourais.Include(s => s.ArtMartials).FirstOrDefault(s => s.Id == id);
            if (samourai == null)
            {
                return HttpNotFound();
            }
            return View(samourai);
        }

        // GET: Samourais/Create
        public ActionResult Create()
        {
            SamouraisViewModel vm = new SamouraisViewModel
            {
                Armes = db.Armes.Where(a => !db.Samourais.Select(s => s.Arme).Contains(a)).Select(a => new SelectListItem() { Text = a.Nom + " " + a.Degats, Value = a.Id.ToString() }).ToList(),
                ArtMartials = db.ArtMartials.Select(a => new SelectListItem { Text = a.Nom, Value = a.Id.ToString() }).ToList()
            };
            return View(vm);
        }

        // POST: Samourais/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SamouraisViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Samourai s = vm.Samourai;
                s.Arme = db.Armes.FirstOrDefault(a => a.Id == vm.IdArme);
                s.ArtMartials = db.ArtMartials.Where(a => vm.IdArtMartials.Contains(a.Id)).ToList();
                db.Samourais.Add(s);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            vm.Armes = getArmesSelectListItems(vm.Samourai.Id);
            vm.ArtMartials = db.ArtMartials.Select(a => new SelectListItem { Text = a.Nom, Value = a.Id.ToString() }).ToList();
            return View(vm);
        }

        // GET: Samourais/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Samourai samourai = db.Samourais.Include(s => s.ArtMartials).FirstOrDefault(s => s.Id == id);
            if (samourai == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> ArmesListItems = getArmesSelectListItems(samourai.Id);
            SamouraisViewModel vm = new SamouraisViewModel
            {
                Samourai = samourai,
                Armes = ArmesListItems,
                ArtMartials = db.ArtMartials.Select(a => new SelectListItem { Text = a.Nom, Value = a.Id.ToString() }).ToList()
            };

            if (samourai.Arme != null)
            {
                vm.IdArme = samourai.Arme.Id;
            }
            if (samourai.ArtMartials != null && samourai.ArtMartials.Count() > 0)
            {
                vm.IdArtMartials = samourai.ArtMartials.Select(a => a.Id).ToList();
            }

            return View(vm);
        }

        // POST: Samourais/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SamouraisViewModel vm)
        {
            Samourai samourai = db.Samourais.Include(s => s.Arme).Include(s => s.ArtMartials).SingleOrDefault(s => s.Id == vm.Samourai.Id);
            if (ModelState.IsValid)
            {

                samourai.Force = vm.Samourai.Force;
                samourai.Nom = vm.Samourai.Nom;
                samourai.Arme = db.Armes.FirstOrDefault(a => a.Id == vm.IdArme);
                samourai.ArtMartials = db.ArtMartials.Where(a => vm.IdArtMartials.Contains(a.Id)).ToList();
                db.Entry(samourai).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            vm.Armes = getArmesSelectListItems(samourai.Id);
            vm.ArtMartials = db.ArtMartials.Select(a => new SelectListItem { Text = a.Nom, Value = a.Id.ToString() }).ToList();

            return View(vm);
        }

        // GET: Samourais/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Samourai samourai = db.Samourais.Find(id);
            if (samourai == null)
            {
                return HttpNotFound();
            }
            return View(samourai);
        }

        // POST: Samourais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Samourai samourai = db.Samourais.Find(id);
            db.Samourais.Remove(samourai);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private List<SelectListItem> getArmesSelectListItems(int? samouraiId)
        {
            return db.Armes.Where(a => !db.Samourais.Where(s => s.Id != samouraiId).Select(s => s.Arme).Contains(a)).Select(a => new SelectListItem() { Text = a.Nom + " " + a.Degats, Value = a.Id.ToString() }).ToList();
        }
    }
}

TP1-Module06/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Samourais", "Index", "Samourais")</li>
                    <li>@Html.ActionLink("Armes", "Index", "Armes")</li>
                    <li>@Html.ActionLink("Art Martiaux", "Index", "ArtMartials")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TP1-Module06/Views/Shared/_Samourai.cshtml
@model TP1_Module06.Models.SamouraisViewModel


<h4>Samourai</h4>
<hr />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })

<div class="form-group">
    @Html.LabelFor(model => model.Samourai.Force, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Samourai.Force, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Samourai.Force, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Samourai.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Samourai.Nom, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Samourai.Nom, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Samourai.Arme, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.IdArme, Model.Armes, "Choisir une arme", htmlAttributes : new { @class = "form-control" } )
        @Html.ValidationMessageFor(model => model.IdArme, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Samourai.ArtMartials, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.ListBoxFor(model => model.IdArtMartials, Model.ArtMartials, htmlAttributes : new { @class = "form-control", size = Model.ArtMartials.Count() })
        @Html.ValidationMessageFor(model => model.IdArtMartials, "", new { @class = "text-danger" })
    </div>
</div>